<!DOCTYPE html>
<html lang="en">  
<?php require_once('db.php');
	require_once('head1.php'); ?>
	
<style>
body{color:#5b5b5b;
    font-size:15px;}
header{
	position:fixed !important;
	background:#000 !important;	
}
.full-container{
	margin-top:84px;
	overflow-x:hidden;
	background-color:#f9f9f9;
}
a.dashboard_menu, a.dashboard_menu:hover{
	background-color:#f9f9f9 !important;
	color:#7323DC !important;
	border-bottom:none !important;
	font-weight:bold !important;
	border-top:5px solid #7323dc !important;
	padding-top:7px !important;
}
.headdark
{
	font-weight:bolder;
	margin-left:-15px;
}
.left_margin ul li, .left_margin ol li{margin-bottom:10px; margin-left:30px;}

</style>

    
    <!-- NAVBAR================================================== -->
<body>   
<?php require_once('header1.php');   ?>
<?php	require_once('loginsignup.php'); 	?>	
<!-- pop up start -->
	<div class="container-flude full-container">	
	  <div class="container left_margin" style="width:80%;">		
	    <h3 style="color:#7323dc;"><b>Privacy Policy</b></h3>	
         <p>Meeto. Inc. (the “Company”) hereby stipulates as follows this Privacy Policy (this “Policy”) to appropriately manage User Information including personal information of customers of services (“Services”) provided by the Company.</p>	
		 
		 <h4 class="headdark">1.User Information to be collected and collection method</h4>
<p>“User Information” in this Policy means information related to customer identification, a customer’s action history on communication services, and other information related to customers or the customers terminals generated or stored on customers smartphones, personal computers, or other terminals that the Company collects pursuant to this Policy.
User Information the Company will collect through the Services include the following in accordance with the collection method.
</p>

      <p>(1) Information provided by the customer</p>
	  <p>Information that a customer will provide to use the Services is as follows:</p>
	  <ul>
	  <li>・ Name</li>
	  <li>・ Address</li>
	  <li>・ Telephone number</li>
	  <li>・ Email address</li>
	  <li>・ Date of birth</li>
	  <li>・ Age</li>
	  <li>・ Gender</li>
	  <li>・ Photograph (one with content and in a form separately designated by the Company; hereinafter the same in this Policy)</li>
	  <li>・ Other information inputted by the customer on an input form stipulated by the Company</li>
	  </ul>
     </br>
	  <p>(2) Information that, when a customer permits linkage with other services in using the Services, is provided by such other services</p>
	  <p>If when using the Services, a customer permits linkage with social network services and other external services, the Company may collect information provided by external services with which linkage has been permitted. </p>
 
     <p>Such information includes the following:</p>
	 <ul>
	  <li>・ IDs and other identification information that a customer uses on such external services</li>
      <li>・ Other information that a customer permits on the privacy settings of such external services disclosure to linkage partners</li>
	</ul></br>
	
	<p>(3) Information the Company collects through the customer’s use of the Services</p>
    <p>The Company may collect access conditions and other information related to the method of using the Services.</p>
    
	<p>Such information includes the following:</p>
     <ul>
	 <li>・ IDs unique to contractual parties or terminals (such as IDs generated by OS (Android ID), owner terminal identification number (UDID), subscriber identity number (IMSI), and MAC address)</li>
	<li>・ Log information</li>
	<li>・ Identification information generated by the use of cookie technology</li>
	<li>・ Location information</li>
	<br>
	<h4 class="headdark">2.Purposes of use</h4>
	<p>(1) User Information will be used for the provision of the Services as stipulated in Paragraph (2) of this Article 2, and may also be used for other purposes as stipulated in Paragraph (3) of this Article 2.
	</p>

     <p>(2) The specific purposes of use of User Information related to the provision of the Services are as follows:
	 </p>
   <p>
	① To accept registration, confirm identification, and calculate use fees;</br>

	② In a case where a customer uses the Services to provide or display the customer’s products or services (“Provide etc.”), to disclose to viewers of the Services the customer’s User Information that is necessary to identify products and services, and to appropriately describe the products and services;</br>

	③ In a case where the customer uses the Services to request provision of products or services for which a third party other than the Company is the seller or host, to disclose to the provider or host of such products or services the customer’s User Information that is necessary for the provision of such products or services, and to appropriately provide such products or services to the customer;</br>

	④ To maintain and protect the Services, improve the accuracy of the recommendation function related to the Services, and otherwise enhance the quality of the Services;</br>

	⑤ To provide explanations and respond to inquiries concerning the Services;</br>

	⑥ To send information regarding after-care services related to the Services, and new products and services;</br>

	⑦ To deal with conduct that violates the Company’s rules, policies and the like (“Rules etc.”) relating to the Services;</br>

	⑧ To give notice of any changes to Rules etc. relating to the Services; and</br>

	⑨ For purposes of use ancillary to the foregoing purposes of use.</br>
	</p>
    <p>(3)Purposes of use other than those set forth in the above Paragraph (2) of this Article 2 are as follows:</p>
	
	<p>
	① To create statistical data processed in a format that cannot identify individuals in relation to the Company’s services;
	(Type of User Information that will be handled)</br>
   <ul>
	<li>・ IDs unique to contractual parties or terminals</li>
	<li>・ Age</li>
	<li>・ Gender</li>
	<li>・ Residential area</li>
	<li>・ Information on messages between job offerers and job seekers</li>
	<li>・ Information regarding screen transitions within pages</li>
	<li>・ Information on favorite meeting</li>
	<li>・ All job offerers and job seekers review information</li>
	<li>・ Settlement amounts and number of settlements</li>
	<li>・ Other log information</li>
	<li>・ Other identification information generated by the use of cookie technology</li>
	<li>・ Location information</li>
  </ul>
  </p>

   <p>
	② To improve the accuracy of the recommendation function related to the Services, and to otherwise distribute or display advertisements of the Company or third parties
	(Type of User Information that will be handled)</p>
   <ul>
	 <li>・ IDs unique to contractual parties or terminals</li>
	<li>・ Age</li>
	<li>・ Gender</li>
	<li>・ Residential area</li>
	<li>・ Information on messages between job offerers and job seekers</li>
	<li>・ Information regarding screen transitions within pages</li>
	<li>・ Information on favorite meeting</li>
	<li>・ All job offerers and job seekers review information</li>
	<li>・ Settlement amounts and number of settlements</li>
	<li>・ Other log information</li>
	<li>・ Identification information generated by the use of cookie technology</li>
	<li>・ Location information</li>
	</ul>

 <p>
	③ To use for marketing and other information analysis
	(Type of User Information that will be handled)</p>
   <ul>
	<li>・ Name</li>
	<li>・ Email address</li>
	<li>・ Date of birth</li>
	<li>・ Age</li>
	<li>・ Gender</li>
	<li>・ Residential area</li>
	<li>・ Information on messages between job offerers and job seekers</li>
	<li>・ Information regarding screen transitions within pages</li>
	<li>・ Information on favorite meeting</li>
	<li>・ All job offerers and job seekers review information</li>
	<li>・ Settlement amounts and number of settlements</li>
	<li>・ Other information inputted by the customer on an input form stipulated by the Company</li>
  </ul>
	<br>
	<h4 class="headdark">3.Method of requesting discontinuation of use</h4>
	<p>By performing the prescribed settings for the Services, the customer may request discontinuation of use of all or part of his/her User Information; in such a case, in accordance with the Company’s stipulations, the Company will promptly discontinue such use. Depending on the type of User Information, the collection or use of such information may be a condition to the Services, and in such a case, if and only if the customer cancels the Services in a manner prescribed by the Company, the Company will discontinue such collection.</p>
<br>
	<h4 class="headdark">4.Consent to provision of User Information to third parties</h4>
	<p>Before using the Services, a customer must consent to the provision of User Information by the Company to third parties as set forth below.</p>

	<p>(1) If a customer intends to use the Services and register his/her products or services, disclosure by the Company to the viewers of the Services of the following user information necessary to identify the products or services the customer registers.</br>
	(User Information that will be provided)</br>
	The customer’s ID, nickname, thumbnail image, user evaluation, and other information regarding products or services that the customer provides that the customer inputs or Provides etc. on an input form stipulated by the Company.
	</p>

	<p>(2) If a customer intends to use the Services and carry out procedures relating to products or services that the Services Provide etc., disclosure by the Company of the following User Information to persons who Provide etc. such products or services.</br>
	(User Information that will be provided)</br>
	The customer’s name, telephone number, email address, and other information that the customer inputs or Provides etc. on an input form stipulated by the Company through the Services use procedures.
	</p>
</br>
	<h4 class="headdark">5.Provision of personal information to third parties</h4>
	<p>Without obtaining prior consent under the preceding paragraph, unless permitted under the Personal Information Protection Act or other laws and regulations, the Company will not provide any User Information that is personal information to third parties without obtaining the prior consent of the customer; provided, however, that the following will not apply in the following cases:</p>

	<p>
	① If the Company outsources the handling of personal information in whole or in part within the scope necessary to realize the use purposes;</br>

	② If personal information is provided in conjunction with a merger or other business succession;</br>
	
	③If, in a case where it is necessary to cooperate with a government agency, local public agency, or a person entrusted by either of the foregoing in the carrying out of work stipulated under laws and regulations, the act of obtaining the consent of the customer is likely to hinder such work; or</br>

	④If otherwise permitted under the Personal Information Protection Act or other laws and regulations</br>
	</p>
</br>
	<h4 class="headdark">6.Safety management for protection of personal information</h4>
	<p>The Company will stipulate rules to protect personal information it acquires, publicize and emphasize such rules to its employees, and work towards maintaining and enhancing safety management measures necessary to protect the personal information acquired by the Company.</p>
</br>
	<h4 class="headdark">7.Disclosure of personal information</h4>
	<p>If a customer requests disclosure of personal information pursuant to the stipulations of the Personal Information Protection Act, after confirming that such request is from the customer himself/herself or a legitimate agent (presentation of personal identification documents may be requested), the Company will make disclosure to the customer without delay (if the relevant personal information does not exist, the customer will be notified to that effect); provided, however, that the foregoing will not apply in cases where the Company is not obligated to make disclosure under the Personal Information Protection Act or other laws and regulations. It should be noted in advance that there will be a fee (3,000 yen per request) for disclosure of personal information.</p>
</br>
	<h4 class="headdark">8.Correcting and discontinuing use etc. of personal information</h4>
	<p>
	(1)If (i) on the grounds that personal information is not true, a customer requests correction of the content of such information pursuant to the Personal Information Protection Act, or (ii) on the grounds that personal information is being handled beyond the scope of use purposes announced in advance or that personal information was obtained through deceit or other unauthorized means, a customer requests discontinuation of use of personal information pursuant to the Personal Information Protection Act, after confirming that the request is from the customer himself/herself, the Company will perform the necessary investigation without delay, and on the basis of the findings of such investigation, correct the content of or discontinue the use of personal information, and notify the customer to that effect. If the Company decides not to correct or discontinue use based on a valid reason, the customer will be notified to that effect.</p>
    <p>
	(2)If a customer requests removal of his/her personal information, and the Company determines that it is necessary to comply with such request, after confirming that the request is from the customer himself/herself, the Company will remove the personal information, and notify the customer to that effect.</p>

	<p>(3)If under the Personal Information Protection Act or other laws and regulations, the Company is not obligated to carry out correction etc. or discontinuation of use etc., the preceding two paragraphs will not apply.</p>
	
	</br>
	<h4 class="headdark">9.Contact point for inquiries</h4>
	<p>Opinions, questions, complaints, and other inquiries concerning the handling of User Information should be addressed to the following:</p>

	<p>Address: 1-16-32 Momochi, Sawara-ku, Fukuoka-shi, Fukuoka Pref. 814-0006 JAPAN </p>

	<p>Meeto  Inc., Person in charge: Yuki Matsuzuka</br>
	E-mail：meeto.japan@gmail.com</p>
</br>
	<h4 class="headdark">10.Procedures to amend this Policy</h4>
	<p>The Company will perform appropriate reviews of the state of operations relating to the handling of User Information, work towards continuous improvement, and may amend this Policy when necessary. If this Policy is amended, customers will be notified by posting on the Company’s webpage; provided, however, that for amendments that require the consent of customers under laws and regulations, the consent of customers will be obtained by methods prescribed by the Company.
	</p>
	 </div>
	</div>
</div>

<div class="top-margin-20"></div>

<?php
require_once('footer1.php');
?>
<!-- footer END-->



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="js/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="js/ie10-viewport-bug-workaround.js"></script>